name: SonarCloud Analysis

on:
  push:
    branches:
      - 'main'
      - 'feature/sonarqube'

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for better results
          
      - name: Install Node.js manually
        run: |
          curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node -v
          npm -v
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps && npm install reflect-metadata --save
        
      - name: Run tests
        run: cd backend && npm test --coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dojo-import:
    needs: sonarcloud
    runs-on: ubuntu-latest
    if: needs.sonarcloud.result == 'success'
    steps:
      - name: Import Sonar findings into DefectDojo
        env:
          DOJO_URL: ${{ secrets.DOJO_URL }}
          DOJO_TOKEN: ${{ secrets.DOJO_TOKEN }}
        run: |
          curl -s -S -X POST "${DOJO_URL}/api/v2/import-scan/" \
            -H "Authorization: Token ${DOJO_TOKEN}" \
            -F scan_type="SonarQube API Import" \
            -F tool_config_id=1 \
            -F sonar_project_key="alearasan_MapYourWorld" \
            -F sonar_branch="main" \
            -F product_name="MapYourWorld Fork" \
            -F engagement_name="Interactive test" \
            -F auto_create_context=true \
            -F push_to_git_provider=true
